project:
  type: website
  output-dir: "."

website:
  title: "Workshops por palestina"
  navbar:
    left:
      - href: index.qmd
        text: Principal
      - href: historial.qmd
        text: Historial

format:
  html:
    theme: litera
    css:
      - https://raw.githubusercontent.com/AGSCL/Workshops-por-palestina/refs/heads/master/mylibs/styles.css
    toc: true
    toc-location: left
    number-sections: true
    smooth-scroll: true
execute:
  freeze: false

