project:
  type: website
  output-dir: "."

website:
  title: "Workshops por palestina"
  navbar:
    left:
      - href: index.qmd
        text: Principal
      - href: historial.qmd
        text: Historial

format:
  html:
    theme: litera
    lang: es
    self-contained: true
    css: mylibs/styles.css
    toc: true
    toc-location: left
    number-sections: true
    smooth-scroll: true
execute:
  freeze: false

